### PR TITLE
Add support for statefulsets.

### PR DESCRIPTION
**Pull request by iocanel**
This pull request provides an implementation of #79.

It treats statefulsets like deployments, which appear on the overview page or can be selected using the overview view.

### CODE REVIEW

**Comment by chrisbarrett** [comment]
Thanks very much for the PR. :D I have to look into the failing CI builds for this project, so that's holding me up on hitting merge. Once I've fixed that I'll give this a proper review and look at merging.

**Comment by ageekymonk** [comment]
@iocanel can you do a rebase and raise a pull request again. I have fixed the build issues.

**Comment by dkrieger** [comment]
What is the status here? @ageekymonk @iocanel 

Anything I can do to get this merged?

**Comment by olymk2** [comment]
Can this be merged @ageekymonk @iocanel be nice to see this and the ingress pr merged :)

**Comment by noorul** [comment]
This is done via #105

@iocanel Can you close this?

**Pull request closed without merging**
