### PR TITLE
Persistentvolumeclaims

### PR DESCRIPTION
**Pull request by Walheimat**
This adds a new overview for persistent volume claims.

It also adds new tests.

**I failed to update the dependency graph**. If you are interested in adding this, let me know how I can generate it.

I'm also not 100% sure I did everything correctly.

### CODE REVIEW

**Comment by Walheimat** [comment]
Looks like I greatly decreased coverage, oops, will address tomorrow.

**Comment by Walheimat** [comment]
Hm, not sure why the pipeline fails now, don't think it should be those changes, so I'll wait for comments as to what else I should change so a proper commit triggers it again.

**Comment by noorul** [comment]
Are the tests passing locally?

**Comment by Walheimat** [comment]
tests
Yes, they do.

**Comment by noorul** [comment]
I re-triggered the jobs

**Comment by Walheimat** [comment]
Cool, thanks. I'll see if I can get to a net plus for the coverage tomorrow.

**Comment by Walheimat** [comment]
Hi, I couldn't find a way to increase the coverage, so instead I tried to fix drawing the dependency graph. I also added the updated results (which looks a bit busy now).

**Review by noorul — CHANGES_REQUESTED** [review]
Some minor comments. Also please squash your commits.

**Comment by Walheimat** [comment]
> Some minor comments. Also please squash your commits.

All good now?

**Review by noorul — CHANGES_REQUESTED** [review]
I tried to test this locally. I see that alignments are not proper.
Screenshot 2021-11-13 at 12 38 02 PM

**Comment by Walheimat** [comment]
Hot damn!

**Comment by Walheimat** [comment]
Can you pull and try again please?

**Comment by noorul** [comment]
LGTM

**Review by noorul — APPROVED** [review]

**Comment by noorul** [comment]
Thank you @Walheimat for adding this resource.

**Pull request merged**
