### PR TITLE
Enable proxy server management

### LINKED ISSUE #247: Support enabling/disabling proxy, with display in overview of proxy status
## Overview

In order to implement functionality such as #235, we "need" the ability to enable `kubectl proxy` so that we can send requests to and receive responses from the Kubernetes API (see [this comment](https://github.com/kubernetes-el/kubernetes-el/issues/235#issuecomment-995492381) for details).

We can implement macros such as `kubernetes--with-proxy` (see #243) that enable the proxy when it's not already active, but a naive implementation of such a macro would leave the proxy running after the fact, which may not be desirable. In the absence of the ability to associate a process -- like the proxy one -- with a TTL for auto-termination, we should make it:
1. Very obvious to users when the proxy is active;
2. Very easy to disable the proxy if it is.

Plus this functionality would be good to have for completeness's sake regardless.

## Definition of Done

- Overview buffer shows the proxy status ("enabled/disabled");
- Users can enable/disable the proxy via a transient

### PR DESCRIPTION
**Pull request by jinnovation**
Closes #247.

With this addition, users can now start up and terminate kubectl proxy servers via `P P`, with overview buffer updating to reflect the status thereof.

### CODE REVIEW

**Comment by jinnovation** [comment]
I'll be adding unit tests, but wanted to open this up for review in advance

**Comment by jinnovation** [comment]
> I'll be adding unit tests, but wanted to open this up for review in advance

Done.

**Comment by jinnovation** [comment]
@noorul: This PR is now ready for your review. I've decomposed some of its previous larger scope into smaller PRs (thanks for your reviews on those) that I've merged in in advance of this one; hopefully that makes this one easier to review.

**Review by noorul — APPROVED** [review]
LGTM. I could not find time to test this manually.

**Pull request merged**
